language: ruby
rvm:
  - 2.3.0
env:
  - ADMIN_CREDENTIALS="Basic YWRtaW46cGFzc3dvcmTCow=="
services:
  - postgresql
branches:
  only:
    - master
    - production
before_script:
  - psql -c 'create database legislated_test;' -U postgres
deploy:
  provider: heroku
  run: rake db:migrate
  api_key:
    secure: M2mm8Vfhu+fhZfu209+xvh3lt4RSV3joMTkH2cd/5TjV7tjAfXmLRNonL484mx8PDHfABA8aNqVKsQITg5THedIHZmVxpYZN61BkBfsV9tYBhe6idXFsj7qymh2OCXR0O4ANkTt+s3da+cvK58nsiINFlwgr/CqSoUnveKbClk3nFC86Ax5Maek6SxX2b86BFfit4Gfe3zu39JoHElOKJzRHm3peFG9qL5q27b9fscIbWPImjAnFGWyudnlh2Q16m8PX8HF9+Mak73vHQBBsNRDvmFMFcMqwTQqGc1+/xZcJ0Bd119jSNYvS602Eu68flt5W8BOH7VOaXwcWWC2k7zWyzZ31ChMsTlMu0TzXygNC2UCV4faFZpPi9vGQ2Zvh/6IfPxK1bZH5AlOynxJKPwWFKPQptdqCAQKoSha3l6rSvy+nqRmOpGg1VFYZRQtkRVYSijXhLO3UhBNyZO+ewYJ8napYaLWdU3J07wTOto+YfqvGaHIisChdQqd4SuldIbUAp7ZS/Nxwg4XMGVywnO2Po5yllsjSNqBZu0dOKil9Gyg6W7rd7JdM5V013ksRlq424rZ4YKAfTI1j6QTcl6fJYJmaQnkGagPmiwA9pHT+3XhdKMyzflT4nUyM4+6ZwPUgLNDr1tvnEFSQuLHS4Vww6P7Zh3KIn0To7Vl5nsM=
  app:
    master: legislated-staging
    production: legislated
